### ISSUE TITLE
Segmentation fault with -DUSE_LTE_RATES=True

### ISSUE THREAD

**Issue by ttsou** [srsLTE/srsLTE#175]
Use of standard radix-2 rates causes segmentation fault in upper RRC layer. Bisect traces to commit ed863e9d14645cdf98079c5900e4afc337f8d477 - revert prevents the crash from ocuring.

**Crash message**
```
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...
---  exiting  ---
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```

**Backtrace**
```
Thread 1 "srsenb" received signal SIGSEGV, Segmentation fault.
srsenb::rrc::generate_sibs (this=this@entry=0x7ffff18bf110)
    at /home/ttsou/srs/srsLTE_testers/srsenb/src/upper/rrc.cc:135
135	    msg[msg_index].N_sibs = 0;
(gdb) bt
#0  srsenb::rrc::generate_sibs (this=this@entry=0x7ffff18bf110)
    at /home/ttsou/srs/srsLTE_testers/srsenb/src/upper/rrc.cc:135
#1  0x0000555555600176 in srsenb::rrc::init (this=this@entry=0x7ffff18bf110, 
    cfg_=cfg_@entry=0x7ffffff65290, phy_=phy_@entry=0x7ffff17bd310, 
    mac_=mac_@entry=0x7ffff18bc528, rlc_=rlc_@entry=0x7ffff18bf030, 
    pdcp_=pdcp_@entry=0x7ffff18bf0b0, s1ap_=0x7ffff19fefa0, gtpu_=0x7ffff19feec0, 
    log_rrc=0x7ffff1a09c90)
    at /home/ttsou/srs/srsLTE_testers/srsenb/src/upper/rrc.cc:60
#2  0x00005555555dfb2a in srsenb::enb::init (this=0x7fffe2d5d010, 
    args_=<optimized out>) at /home/ttsou/srs/srsLTE_testers/srsenb/src/enb.cc:219
#3  0x00005555555cfaf5 in main (argc=2, argv=0x7fffffffe0e8)
    at /home/ttsou/srs/srsLTE_testers/srsenb/src/main.cc:378
```

**Git bisect log**
```
[ttsou@betty srsLTE ((60bc6343...)|BISECTING)]$ git bisect log
git bisect start
# bad: [8f9ce13b1cb1892ba971dba66f49f6e4e579ecaa] Merge branch 'next' of github.com:softwareradiosystems/srsLTE into next
git bisect bad 8f9ce13b1cb1892ba971dba66f49f6e4e579ecaa
# good: [7a14e2883748bf48cf1accb7222f79c2be0f2497] Extened to all US MCC codes
git bisect good 7a14e2883748bf48cf1accb7222f79c2be0f2497
# good: [26017a8f98244218d8be1661b290d91da67e8595] Fixed double const warning
git bisect good 26017a8f98244218d8be1661b290d91da67e8595
# good: [4b62c9cb0652d2314d54dbe8dba750affe61be20] Merge branch 'next' into epc.
git bisect good 4b62c9cb0652d2314d54dbe8dba750affe61be20
# bad: [eac2b6e43c8e8fb2db7cf7879d9294d3893327ab] Merge branch 'next'
git bisect bad eac2b6e43c8e8fb2db7cf7879d9294d3893327ab
# bad: [464357d88c1eb161c14f529ab832856b76a7d911] Merge branch 'next' of github.com:softwareradiosystems/srsLTE into next
git bisect bad 464357d88c1eb161c14f529ab832856b76a7d911
# good: [8670b4f2584fb85ca0d6dd1cd33841107ea71301] Update README.md
git bisect good 8670b4f2584fb85ca0d6dd1cd33841107ea71301
# bad: [68b37a74b53d9cdf28dee784593d5e5b5a7ee3c6] Merge branch 'master' of github.com:srsLTE/srsLTE
git bisect bad 68b37a74b53d9cdf28dee784593d5e5b5a7ee3c6
# bad: [415b528aff7df51cfdd582ca45a0086766f1186e] Fixed MME IP address in default ENB configuration
git bisect bad 415b528aff7df51cfdd582ca45a0086766f1186e
# bad: [ab061b38d3c80796d5ec7f8f8a28794c0f49cb2d] Merge pull request #135 from mrlnc/sib_config_pr
git bisect bad ab061b38d3c80796d5ec7f8f8a28794c0f49cb2d
# bad: [ed863e9d14645cdf98079c5900e4afc337f8d477] Fix SIB config issue #134 and add comments
git bisect bad ed863e9d14645cdf98079c5900e4afc337f8d477
# good: [60bc634386ee2f9f3400d84a22fa0655137119f9] Fix build if WRITE_SIB_PCAP is defined
git bisect good 60bc634386ee2f9f3400d84a22fa0655137119f9
# first bad commit: [ed863e9d14645cdf98079c5900e4afc337f8d477] Fix SIB config issue #134 and add comments
```
**Environment**
```
RF Device - USRP B210
Version - Linux; GNU C++ version 7.2.0; Boost_106200; UHD_3.11.0.3.11.0.1-0-ga1b5c4ae
Build - "-DCMAKE_BUILD_TYPE=DEBUG -DUSE_LTE_RATES=True"
Config - Default
```

**Comment by ismagom** [comment]
Fixed in 33f6a3513a719619dc309e8f0bc1ad57403408c6
